let data = [
  {
    "name": "vim",
    "description": "One of the two classic highly configurable and extensible terminal based text editors",
    "link": "https://www.vim.org/",
    "repository": "https://github.com/vim/vim",
    "written in": "C, vimscript",
    "gui or terminal": "terminal",
    "modes": "yes",
    "lsp": "plugin",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "(1991-11-02)",
    "latest release": "9.2.0888 (2026-07-31)",
    "license": "GPL-compatible"
  }, {
    "name": "neovim",
    "description": "Vim-fork focused on extensibility and usability",
    "link": "https://www.neovim.io/",
    "repository": "https://github.com/neovim/neovim",
    "written in": "C, vimscript, lua",
    "gui or terminal": "terminal",
    "modes": "yes",
    "lsp": "plugin",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "0.1.0 (2015-01-01)",
    "latest release": "0.12.4 (2026-07-05)",
    "license": "Apachev2"
  }, {
    "name": "Emacs",
    "description": "The other one of the two classic highly configurable and extensible terminal based text editors",
    "link": "https://www.gnu.org/software/emacs/",
    "repository": "https://cgit.git.savannah.gnu.org/cgit/emacs.git",
    "written in": "C, Emacs lisp",
    "gui or terminal": "terminal",
    "modes": "yes",
    "lsp": "plugin",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "(1984)",
    "latest release": "31.0.91 (2026-07-23)",
    "license": "GPLv3"
  }, {
    "name": "micro",
    "description": "A modern and intuitive terminal-based text editor",
    "link": "https://micro-editor.github.io/",
    "repository": "https://github.com/zyedidia/micro",
    "written in": "Go, Lua",
    "gui or terminal": "terminal",
    "modes": "no",
    "lsp": "no",
    "ai": "no",
    "plugins": "yes",
    "first release": "2016-08-29",
    "latest release": "2.0.15 (2025-12-31)",
    "license": "MIT"
  }, {
    "name": "Kakoune ",
    "description": "A code editor with a strong focus on interactivity and multiple selections",
    "link": "https://kakoune.org/",
    "repository": "https://github.com/mawww/kakoune",
    "written in": "C++, KakouneScript",
    "gui or terminal": "terminal",
    "modes": "yes",
    "lsp": "plugin",
    "ai": "no",
    "plugins": "yes",
    "first release": "2018.04.13",
    "latest release": "2026.05.21 (2026-05-21)",
    "license": "Unilicense"
  }, {
    "name": "Helix ",
    "description": "A post-modern modal text editor inspired by Kakoune and Neovim",
    "link": "https://helix-editor.com/",
    "repository": "https://github.com/helix-editor/helix",
    "written in": "Rust",
    "gui or terminal": "terminal",
    "modes": "yes",
    "lsp": "yes",
    "ai": "no",
    "plugins": "no",
    "first release": "0.0.2 (2021-05-21)",
    "latest release": "25.07.1 (2025-07-18)",
    "license": "MPLv2"
  }, {
    "name": "editor",
    "description": "A simple and fast GUI text editor inspired by the acme editor from Plan 9",
    "link": "https://github.com/jmigpin/editor",
    "repository": "https://github.com/jmigpin/editor",
    "written in": "Go",
    "gui or terminal": "gui",
    "modes": "no",
    "lsp": "yes",
    "ai": "no",
    "plugins": "yes",
    "first release": "1.0.0 (2020-01-03)",
    "latest release": "3.14.0 (2026-07-17)",
    "license": "MIT"
  }, {
    "name": "kilo (in Go)",
    "description": "A small and simple terminal-based text editor written in a single file with just 1000 lines of Go",
    "link": "https://github.com/bediger4000/kilo-in-go",
    "repository": "https://github.com/bediger4000/kilo-in-go",
    "written in": "Go",
    "gui or terminal": "terminal",
    "modes": "no",
    "lsp": "no",
    "ai": "no",
    "plugins": "no",
    "first release": "2017-07-17",
    "latest release": "2017-07-17",
    "license": "none"
  }, {
    "name": "jedit",
    "description": "A programmer's text editor written in Java. It can be configured as a rather powerful IDE through the use of its plugin architecture.",
    "link": "https://www.jedit.org/",
    "repository": "https://sourceforge.net/p/jedit/jEdit/ci/master/tree/",
    "written in": "Java",
    "gui or terminal": "gui",
    "modes": "no",
    "lsp": "no",
    "ai": "no",
    "plugins": "yes",
    "first release": "0.2 (1998-09-02)",
    "latest release": "5.7.0 (2024-08-03)",
    "license": "GPLv2"
  }, {
    "name": "Lite XL",
    "description": "A lightweight text editor written in Lua.",
    "link": "https://lite-xl.com/",
    "repository": "https://github.com/lite-xl/lite-xl",
    "written in": "C, Lua",
    "gui or terminal": "gui",
    "modes": "no",
    "lsp": "yes",
    "ai": "no",
    "plugins": "yes",
    "first release": "1.0 (2019-12-28)",
    "latest release": "2.1.8 (2025-06-09)",
    "license": "MIT"
  }, {
    "name": "Geany",
    "description": "A small and lightweight IDE",
    "link": "https://www.geany.org/",
    "repository": "https://github.com/geany/geany",
    "written in": "C, C++",
    "gui or terminal": "gui",
    "modes": "no",
    "lsp": "plugin",
    "ai": "no",
    "plugins": "yes",
    "first release": "0.4.0 (2005-12-21)",
    "latest release": "2.1 (2025-07-06)",
    "license": "GPLv2"
  }, {
    "name": "Fleet",
    "description": "Editor made by JetBrains, with support for multiple languages and AI assistant",
    "link": "https://www.jetbrains.com/fleet/",
    "repository": "https://www.jetbrains.com/fleet/",
    "written in": "Kotlin",
    "gui or terminal": "gui",
    "modes": "no",
    "lsp": "yes",
    "ai": "yes",
    "plugins": "yes",
    "first release": "1.0 (2021-11-29)",
    "latest release": "1.47 (2025-06-21)",
    "license": "commercial (public preview)"
  }, {
    "name": "Gnome Builder",
    "description": "An IDE for writing GNOME-based software.",
    "link": "https://apps.gnome.org/de/Builder/",
    "repository": "https://gitlab.gnome.org/GNOME/gnome-builder",
    "written in": "C",
    "gui or terminal": "gui",
    "modes": "no",
    "lsp": "yes",
    "ai": "no",
    "plugins": "yes",
    "first release": "3.16.0 (2015-03-24)",
    "latest release": "50.0 (2026-03-17)",
    "license": "GPLv3"
  }, {
    "name": "IntelliJ Community Edition",
    "description": "Professional Java IDE",
    "link": "https://www.jetbrains.com/idea/",
    "repository": "https://github.com/JetBrains/intellij-community",
    "written in": "Java, Kotlin",
    "gui or terminal": "gui",
    "modes": "plugin",
    "lsp": "yes",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "1.0 (2001-01)",
    "latest release": "2026.2.0.1 (2026-07-27)",
    "license": "Apachev2"
  }, {
    "name": "Kate",
    "description": "Advanced text editor of the KDE project.",
    "link": "https://kate-editor.org",
    "repository": "https://invent.kde.org/utilities/kate",
    "written in": "C++",
    "gui or terminal": "gui",
    "modes": "plugin",
    "lsp": "yes",
    "ai": "no",
    "plugins": "yes",
    "first release": "1.0 (2001-08-15)",
    "latest release": "26.07.90 (2026-07-30)",
    "license": "LGPLv2, MIT"
  }, {
    "name": "VSCodium",
    "description": "VSCodium is a community-driven, freely-licensed binary distribution of Microsoft’s editor VS Code.",
    "link": "https://vscodium.com/",
    "repository": "https://github.com/VSCodium/vscodium",
    "written in": "TypeScript, JavaScript",
    "gui or terminal": "gui",
    "modes": "plugin",
    "lsp": "yes",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "1.26.0 (2018-08-15)",
    "latest release": "1.126.04524 (2026-01-15)",
    "license": "MIT"
  }, {
    "name": "Zed",
    "description": "Zed is a minimal code editor crafted for speed and collaboration with humans and AI.",
    "link": "https://zed.dev/",
    "repository": "https://github.com/zed-industries/zed",
    "written in": "Rust",
    "gui or terminal": "gui",
    "modes": "yes (optional)",
    "lsp": "yes",
    "ai": "yes",
    "plugins": "yes",
    "first release": "v0.1 (2021-01-08)",
    "latest release": "v1.13.1  (2026-07-29)",
    "license": "AGPL, GPL, Apache"
  }, {
    "name": "Lapce",
    "description": "Lightning-fast and Powerful Code Editor ",
    "link": "https://lap.dev/lapce/",
    "repository": "https://github.com/lapce/lapce",
    "written in": "Rust",
    "gui or terminal": "gui",
    "modes": "yes (optional)",
    "lsp": "yes",
    "ai": "yes",
    "plugins": "yes",
    "first release": "v0.0.1 (2021-10-06)",
    "latest release": "v0.4.6 (2026-01-21)",
    "license": "Apachev2"
  }, {
    "name": "Pulsar",
    "description": "Pulsar is a fork of the discontinued Atom editor - assuming its mission of being a zero-compromise combination of hackability and usability.",
    "link": "https://pulsar-edit.dev/",
    "repository": "https://github.com/pulsar-edit/pulsar",
    "written in": "JavaScript",
    "gui or terminal": "gui",
    "modes": "plugin",
    "lsp": "yes",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "v1.102.0 (2023-02-16)",
    "latest release": "v1.132.1 (2026-05-21)",
    "license": "MIT"
  }, {
    "name": "chr",
    "description": "The chr terminal editor is inspired by the turbo pascal editor.",
    "link": "https://github.com/chr-editor/chr",
    "repository": "https://github.com/chr-editor/chr",
    "written in": "C++",
    "gui or terminal": "terminal",
    "modes": "no",
    "lsp": "no",
    "ai": "no",
    "plugins": "no",
    "first release": "v0.1.75 (2023-12-23)",
    "latest release": "v0.1.81 (2025-11-16)",
    "license": "BSLv1"
  }, {
    "name": "Theia",
    "description": "Eclipse Theia is an extensible framework to develop full-fledged multi-language Cloud & Desktop IDEs and tools with state-of-the-art web technologies.",
    "link": "https://theia-ide.org/",
    "repository": "https://github.com/eclipse-theia/theia",
    "written in": "TypeScript",
    "gui or terminal": "gui",
    "modes": "plugin",
    "lsp": "yes",
    "ai": "plugin",
    "plugins": "yes",
    "first release": "0.12.0 (2020-05-19",
    "latest release": "1.74.0 (2026-07-31)",
    "license": "EPLv2, GPLv2, MIT"
  }, {
    "name": "Atom",
    "description": "Atom is a hackable text editor for the 21st century.",
    "link": "https://atom-editor.cc/",
    "repository": "https://github.com/atom/atom",
    "written in": "JavaScript",
    "gui or terminal": "gui",
    "modes": "plugin",
    "lsp": "plugin",
    "ai": "no",
    "plugins": "yes",
    "first release": "2014-02-26",
    "latest release": "1.60.0 (2022-05-08)",
    "license": "MIT"
  }, {
    "name": "Microsoft edit",
    "description": "This editor pays homage to the classic MS-DOS Editor, but with a modern interface and input controls similar to VS Code.",
    "link": "https://github.com/microsoft/edit",
    "repository": "https://github.com/microsoft/edit",
    "written in": "Rust",
    "gui or terminal": "terminal",
    "modes": "no",
    "lsp": "no",
    "ai": "no",
    "plugins": "no",
    "first release": "1.0.0 (2025-05-19)",
    "latest release": "2.0.0 (2026-04-22)",
    "license": "MIT"
  }, {
    "name": "nano",
    "description": "Small and friendly text editor. It copies the look and feel of Pico.",
    "link": "https://www.nano-editor.org/",
    "repository": "https://https.git.savannah.gnu.org/git/nano.git/",
    "written in": "C",
    "gui or terminal": "terminal",
    "modes": "no",
    "lsp": "no",
    "ai": "no",
    "plugins": "no",
    "first release": "0.5.0 (1999-11-18)",
    "latest release": "9.2 (2026-07-31)",
    "license": "GPLv3"
  }
];
